/* 
 * Synacta
 *
 * WebApi
 *
 * OpenAPI spec version: v1
 * Contact: bhofmann@agile-is.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Organisation
    /// </summary>
    [DataContract]
    public partial class Organisation :  IEquatable<Organisation>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Organisation" /> class.
        /// </summary>
        /// <param name="ID">ID.</param>
        /// <param name="Name">Name.</param>
        /// <param name="ParentID">ParentID.</param>
        /// <param name="ParentName">ParentName.</param>
        /// <param name="HasChildren">HasChildren.</param>
        /// <param name="Children">Children.</param>
        /// <param name="OdataCount">OdataCount.</param>
        /// <param name="OdataContext">OdataContext.</param>
        /// <param name="OdataReadLink">OdataReadLink.</param>
        /// <param name="ChildodataNavigationLink">ChildodataNavigationLink.</param>
        /// <param name="ParentodataNavigationLink">ParentodataNavigationLink.</param>
        /// <param name="FullODataLinkodataNavigationLink">FullODataLinkodataNavigationLink.</param>
        /// <param name="StandardODataLinkodataNavigationLink">StandardODataLinkodataNavigationLink.</param>
        /// <param name="NoneODataLinkodataNavigationLink">NoneODataLinkodataNavigationLink.</param>
        /// <param name="OdataEditLink">OdataEditLink.</param>
        /// <param name="OdataEtag">OdataEtag.</param>
        /// <param name="OdataMetadataEtag">OdataMetadataEtag.</param>
        public Organisation(string ID = null, string Name = null, string ParentID = null, string ParentName = null, bool? HasChildren = null, List<Organisation> Children = null, int? OdataCount = null, string OdataContext = null, string OdataReadLink = null, string ChildodataNavigationLink = null, string ParentodataNavigationLink = null, string FullODataLinkodataNavigationLink = null, string StandardODataLinkodataNavigationLink = null, string NoneODataLinkodataNavigationLink = null, string OdataEditLink = null, string OdataEtag = null, string OdataMetadataEtag = null)
        {
            this.ID = ID;
            this.Name = Name;
            this.ParentID = ParentID;
            this.ParentName = ParentName;
            this.HasChildren = HasChildren;
            this.Children = Children;
            this.OdataCount = OdataCount;
            this.OdataContext = OdataContext;
            this.OdataReadLink = OdataReadLink;
            this.ChildodataNavigationLink = ChildodataNavigationLink;
            this.ParentodataNavigationLink = ParentodataNavigationLink;
            this.FullODataLinkodataNavigationLink = FullODataLinkodataNavigationLink;
            this.StandardODataLinkodataNavigationLink = StandardODataLinkodataNavigationLink;
            this.NoneODataLinkodataNavigationLink = NoneODataLinkodataNavigationLink;
            this.OdataEditLink = OdataEditLink;
            this.OdataEtag = OdataEtag;
            this.OdataMetadataEtag = OdataMetadataEtag;
        }
        
        /// <summary>
        /// Gets or Sets ID
        /// </summary>
        [DataMember(Name="ID", EmitDefaultValue=false)]
        public string ID { get; set; }
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="Name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Gets or Sets ParentID
        /// </summary>
        [DataMember(Name="ParentID", EmitDefaultValue=false)]
        public string ParentID { get; set; }
        /// <summary>
        /// Gets or Sets ParentName
        /// </summary>
        [DataMember(Name="ParentName", EmitDefaultValue=false)]
        public string ParentName { get; set; }
        /// <summary>
        /// Gets or Sets HasChildren
        /// </summary>
        [DataMember(Name="HasChildren", EmitDefaultValue=false)]
        public bool? HasChildren { get; set; }
        /// <summary>
        /// Gets or Sets Children
        /// </summary>
        [DataMember(Name="Children", EmitDefaultValue=false)]
        public List<Organisation> Children { get; set; }
        /// <summary>
        /// Gets or Sets OdataCount
        /// </summary>
        [DataMember(Name="@odata.count", EmitDefaultValue=false)]
        public int? OdataCount { get; set; }
        /// <summary>
        /// Gets or Sets OdataContext
        /// </summary>
        [DataMember(Name="@odata.context", EmitDefaultValue=false)]
        public string OdataContext { get; set; }
        /// <summary>
        /// Gets or Sets OdataReadLink
        /// </summary>
        [DataMember(Name="@odata.readLink", EmitDefaultValue=false)]
        public string OdataReadLink { get; set; }
        /// <summary>
        /// Gets or Sets ChildodataNavigationLink
        /// </summary>
        [DataMember(Name="Child@odata.navigationLink", EmitDefaultValue=false)]
        public string ChildodataNavigationLink { get; set; }
        /// <summary>
        /// Gets or Sets ParentodataNavigationLink
        /// </summary>
        [DataMember(Name="Parent@odata.navigationLink", EmitDefaultValue=false)]
        public string ParentodataNavigationLink { get; set; }
        /// <summary>
        /// Gets or Sets FullODataLinkodataNavigationLink
        /// </summary>
        [DataMember(Name="FullODataLink@odata.navigationLink", EmitDefaultValue=false)]
        public string FullODataLinkodataNavigationLink { get; set; }
        /// <summary>
        /// Gets or Sets StandardODataLinkodataNavigationLink
        /// </summary>
        [DataMember(Name="StandardODataLink@odata.navigationLink", EmitDefaultValue=false)]
        public string StandardODataLinkodataNavigationLink { get; set; }
        /// <summary>
        /// Gets or Sets NoneODataLinkodataNavigationLink
        /// </summary>
        [DataMember(Name="NoneODataLink@odata.navigationLink", EmitDefaultValue=false)]
        public string NoneODataLinkodataNavigationLink { get; set; }
        /// <summary>
        /// Gets or Sets OdataEditLink
        /// </summary>
        [DataMember(Name="@odata.editLink", EmitDefaultValue=false)]
        public string OdataEditLink { get; set; }
        /// <summary>
        /// Gets or Sets OdataEtag
        /// </summary>
        [DataMember(Name="@odata.etag", EmitDefaultValue=false)]
        public string OdataEtag { get; set; }
        /// <summary>
        /// Gets or Sets OdataMetadataEtag
        /// </summary>
        [DataMember(Name="@odata.metadataEtag", EmitDefaultValue=false)]
        public string OdataMetadataEtag { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Organisation {\n");
            sb.Append("  ID: ").Append(ID).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ParentID: ").Append(ParentID).Append("\n");
            sb.Append("  ParentName: ").Append(ParentName).Append("\n");
            sb.Append("  HasChildren: ").Append(HasChildren).Append("\n");
            sb.Append("  Children: ").Append(Children).Append("\n");
            sb.Append("  OdataCount: ").Append(OdataCount).Append("\n");
            sb.Append("  OdataContext: ").Append(OdataContext).Append("\n");
            sb.Append("  OdataReadLink: ").Append(OdataReadLink).Append("\n");
            sb.Append("  ChildodataNavigationLink: ").Append(ChildodataNavigationLink).Append("\n");
            sb.Append("  ParentodataNavigationLink: ").Append(ParentodataNavigationLink).Append("\n");
            sb.Append("  FullODataLinkodataNavigationLink: ").Append(FullODataLinkodataNavigationLink).Append("\n");
            sb.Append("  StandardODataLinkodataNavigationLink: ").Append(StandardODataLinkodataNavigationLink).Append("\n");
            sb.Append("  NoneODataLinkodataNavigationLink: ").Append(NoneODataLinkodataNavigationLink).Append("\n");
            sb.Append("  OdataEditLink: ").Append(OdataEditLink).Append("\n");
            sb.Append("  OdataEtag: ").Append(OdataEtag).Append("\n");
            sb.Append("  OdataMetadataEtag: ").Append(OdataMetadataEtag).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Organisation);
        }

        /// <summary>
        /// Returns true if Organisation instances are equal
        /// </summary>
        /// <param name="other">Instance of Organisation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Organisation other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ID == other.ID ||
                    this.ID != null &&
                    this.ID.Equals(other.ID)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.ParentID == other.ParentID ||
                    this.ParentID != null &&
                    this.ParentID.Equals(other.ParentID)
                ) && 
                (
                    this.ParentName == other.ParentName ||
                    this.ParentName != null &&
                    this.ParentName.Equals(other.ParentName)
                ) && 
                (
                    this.HasChildren == other.HasChildren ||
                    this.HasChildren != null &&
                    this.HasChildren.Equals(other.HasChildren)
                ) && 
                (
                    this.Children == other.Children ||
                    this.Children != null &&
                    this.Children.SequenceEqual(other.Children)
                ) && 
                (
                    this.OdataCount == other.OdataCount ||
                    this.OdataCount != null &&
                    this.OdataCount.Equals(other.OdataCount)
                ) && 
                (
                    this.OdataContext == other.OdataContext ||
                    this.OdataContext != null &&
                    this.OdataContext.Equals(other.OdataContext)
                ) && 
                (
                    this.OdataReadLink == other.OdataReadLink ||
                    this.OdataReadLink != null &&
                    this.OdataReadLink.Equals(other.OdataReadLink)
                ) && 
                (
                    this.ChildodataNavigationLink == other.ChildodataNavigationLink ||
                    this.ChildodataNavigationLink != null &&
                    this.ChildodataNavigationLink.Equals(other.ChildodataNavigationLink)
                ) && 
                (
                    this.ParentodataNavigationLink == other.ParentodataNavigationLink ||
                    this.ParentodataNavigationLink != null &&
                    this.ParentodataNavigationLink.Equals(other.ParentodataNavigationLink)
                ) && 
                (
                    this.FullODataLinkodataNavigationLink == other.FullODataLinkodataNavigationLink ||
                    this.FullODataLinkodataNavigationLink != null &&
                    this.FullODataLinkodataNavigationLink.Equals(other.FullODataLinkodataNavigationLink)
                ) && 
                (
                    this.StandardODataLinkodataNavigationLink == other.StandardODataLinkodataNavigationLink ||
                    this.StandardODataLinkodataNavigationLink != null &&
                    this.StandardODataLinkodataNavigationLink.Equals(other.StandardODataLinkodataNavigationLink)
                ) && 
                (
                    this.NoneODataLinkodataNavigationLink == other.NoneODataLinkodataNavigationLink ||
                    this.NoneODataLinkodataNavigationLink != null &&
                    this.NoneODataLinkodataNavigationLink.Equals(other.NoneODataLinkodataNavigationLink)
                ) && 
                (
                    this.OdataEditLink == other.OdataEditLink ||
                    this.OdataEditLink != null &&
                    this.OdataEditLink.Equals(other.OdataEditLink)
                ) && 
                (
                    this.OdataEtag == other.OdataEtag ||
                    this.OdataEtag != null &&
                    this.OdataEtag.Equals(other.OdataEtag)
                ) && 
                (
                    this.OdataMetadataEtag == other.OdataMetadataEtag ||
                    this.OdataMetadataEtag != null &&
                    this.OdataMetadataEtag.Equals(other.OdataMetadataEtag)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ID != null)
                    hash = hash * 59 + this.ID.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.ParentID != null)
                    hash = hash * 59 + this.ParentID.GetHashCode();
                if (this.ParentName != null)
                    hash = hash * 59 + this.ParentName.GetHashCode();
                if (this.HasChildren != null)
                    hash = hash * 59 + this.HasChildren.GetHashCode();
                if (this.Children != null)
                    hash = hash * 59 + this.Children.GetHashCode();
                if (this.OdataCount != null)
                    hash = hash * 59 + this.OdataCount.GetHashCode();
                if (this.OdataContext != null)
                    hash = hash * 59 + this.OdataContext.GetHashCode();
                if (this.OdataReadLink != null)
                    hash = hash * 59 + this.OdataReadLink.GetHashCode();
                if (this.ChildodataNavigationLink != null)
                    hash = hash * 59 + this.ChildodataNavigationLink.GetHashCode();
                if (this.ParentodataNavigationLink != null)
                    hash = hash * 59 + this.ParentodataNavigationLink.GetHashCode();
                if (this.FullODataLinkodataNavigationLink != null)
                    hash = hash * 59 + this.FullODataLinkodataNavigationLink.GetHashCode();
                if (this.StandardODataLinkodataNavigationLink != null)
                    hash = hash * 59 + this.StandardODataLinkodataNavigationLink.GetHashCode();
                if (this.NoneODataLinkodataNavigationLink != null)
                    hash = hash * 59 + this.NoneODataLinkodataNavigationLink.GetHashCode();
                if (this.OdataEditLink != null)
                    hash = hash * 59 + this.OdataEditLink.GetHashCode();
                if (this.OdataEtag != null)
                    hash = hash * 59 + this.OdataEtag.GetHashCode();
                if (this.OdataMetadataEtag != null)
                    hash = hash * 59 + this.OdataMetadataEtag.GetHashCode();
                return hash;
            }
        }
    }

}
