/* 
 * Synacta
 *
 * WebApi
 *
 * OpenAPI spec version: v1
 * Contact: bhofmann@agile-is.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Container
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContainerTests
    {
        // TODO uncomment below to declare an instance variable for Container
        //private Container instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Container
            //instance = new Container();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Container
        /// </summary>
        [Test]
        public void ContainerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Container
            //Assert.IsInstanceOfType<Container> (instance, "variable 'instance' is a Container");
        }

        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'PropertyInfos'
        /// </summary>
        [Test]
        public void PropertyInfosTest()
        {
            // TODO unit test for the property 'PropertyInfos'
        }
        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Test]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'ObjectType'
        /// </summary>
        [Test]
        public void ObjectTypeTest()
        {
            // TODO unit test for the property 'ObjectType'
        }
        /// <summary>
        /// Test the property 'ParentID'
        /// </summary>
        [Test]
        public void ParentIDTest()
        {
            // TODO unit test for the property 'ParentID'
        }
        /// <summary>
        /// Test the property 'ParentType'
        /// </summary>
        [Test]
        public void ParentTypeTest()
        {
            // TODO unit test for the property 'ParentType'
        }
        /// <summary>
        /// Test the property 'IsVirtual'
        /// </summary>
        [Test]
        public void IsVirtualTest()
        {
            // TODO unit test for the property 'IsVirtual'
        }
        /// <summary>
        /// Test the property 'Frozen'
        /// </summary>
        [Test]
        public void FrozenTest()
        {
            // TODO unit test for the property 'Frozen'
        }
        /// <summary>
        /// Test the property 'HasChild'
        /// </summary>
        [Test]
        public void HasChildTest()
        {
            // TODO unit test for the property 'HasChild'
        }
        /// <summary>
        /// Test the property 'CheckedOutBy'
        /// </summary>
        [Test]
        public void CheckedOutByTest()
        {
            // TODO unit test for the property 'CheckedOutBy'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'OdataContext'
        /// </summary>
        [Test]
        public void OdataContextTest()
        {
            // TODO unit test for the property 'OdataContext'
        }
        /// <summary>
        /// Test the property 'OdataReadLink'
        /// </summary>
        [Test]
        public void OdataReadLinkTest()
        {
            // TODO unit test for the property 'OdataReadLink'
        }
        /// <summary>
        /// Test the property 'ChildodataNavigationLink'
        /// </summary>
        [Test]
        public void ChildodataNavigationLinkTest()
        {
            // TODO unit test for the property 'ChildodataNavigationLink'
        }
        /// <summary>
        /// Test the property 'DocumentodataNavigationLink'
        /// </summary>
        [Test]
        public void DocumentodataNavigationLinkTest()
        {
            // TODO unit test for the property 'DocumentodataNavigationLink'
        }
        /// <summary>
        /// Test the property 'ParentodataNavigationLink'
        /// </summary>
        [Test]
        public void ParentodataNavigationLinkTest()
        {
            // TODO unit test for the property 'ParentodataNavigationLink'
        }
        /// <summary>
        /// Test the property 'FullODataLinkodataNavigationLink'
        /// </summary>
        [Test]
        public void FullODataLinkodataNavigationLinkTest()
        {
            // TODO unit test for the property 'FullODataLinkodataNavigationLink'
        }
        /// <summary>
        /// Test the property 'StandardODataLinkodataNavigationLink'
        /// </summary>
        [Test]
        public void StandardODataLinkodataNavigationLinkTest()
        {
            // TODO unit test for the property 'StandardODataLinkodataNavigationLink'
        }
        /// <summary>
        /// Test the property 'NoneODataLinkodataNavigationLink'
        /// </summary>
        [Test]
        public void NoneODataLinkodataNavigationLinkTest()
        {
            // TODO unit test for the property 'NoneODataLinkodataNavigationLink'
        }
        /// <summary>
        /// Test the property 'OdataEditLink'
        /// </summary>
        [Test]
        public void OdataEditLinkTest()
        {
            // TODO unit test for the property 'OdataEditLink'
        }
        /// <summary>
        /// Test the property 'OdataEtag'
        /// </summary>
        [Test]
        public void OdataEtagTest()
        {
            // TODO unit test for the property 'OdataEtag'
        }
        /// <summary>
        /// Test the property 'OdataMetadataEtag'
        /// </summary>
        [Test]
        public void OdataMetadataEtagTest()
        {
            // TODO unit test for the property 'OdataMetadataEtag'
        }
        /// <summary>
        /// Test the property 'OdataPicklistLink'
        /// </summary>
        [Test]
        public void OdataPicklistLinkTest()
        {
            // TODO unit test for the property 'OdataPicklistLink'
        }

    }

}
