/* 
 * Synacta
 *
 * WebApi
 *
 * OpenAPI spec version: v1
 * Contact: bhofmann@agile-is.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Organisation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrganisationTests
    {
        // TODO uncomment below to declare an instance variable for Organisation
        //private Organisation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Organisation
            //instance = new Organisation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Organisation
        /// </summary>
        [Test]
        public void OrganisationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Organisation
            //Assert.IsInstanceOfType<Organisation> (instance, "variable 'instance' is a Organisation");
        }

        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Test]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ParentID'
        /// </summary>
        [Test]
        public void ParentIDTest()
        {
            // TODO unit test for the property 'ParentID'
        }
        /// <summary>
        /// Test the property 'ParentName'
        /// </summary>
        [Test]
        public void ParentNameTest()
        {
            // TODO unit test for the property 'ParentName'
        }
        /// <summary>
        /// Test the property 'HasChildren'
        /// </summary>
        [Test]
        public void HasChildrenTest()
        {
            // TODO unit test for the property 'HasChildren'
        }
        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Test]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }
        /// <summary>
        /// Test the property 'OdataCount'
        /// </summary>
        [Test]
        public void OdataCountTest()
        {
            // TODO unit test for the property 'OdataCount'
        }
        /// <summary>
        /// Test the property 'OdataContext'
        /// </summary>
        [Test]
        public void OdataContextTest()
        {
            // TODO unit test for the property 'OdataContext'
        }
        /// <summary>
        /// Test the property 'OdataReadLink'
        /// </summary>
        [Test]
        public void OdataReadLinkTest()
        {
            // TODO unit test for the property 'OdataReadLink'
        }
        /// <summary>
        /// Test the property 'ChildodataNavigationLink'
        /// </summary>
        [Test]
        public void ChildodataNavigationLinkTest()
        {
            // TODO unit test for the property 'ChildodataNavigationLink'
        }
        /// <summary>
        /// Test the property 'ParentodataNavigationLink'
        /// </summary>
        [Test]
        public void ParentodataNavigationLinkTest()
        {
            // TODO unit test for the property 'ParentodataNavigationLink'
        }
        /// <summary>
        /// Test the property 'FullODataLinkodataNavigationLink'
        /// </summary>
        [Test]
        public void FullODataLinkodataNavigationLinkTest()
        {
            // TODO unit test for the property 'FullODataLinkodataNavigationLink'
        }
        /// <summary>
        /// Test the property 'StandardODataLinkodataNavigationLink'
        /// </summary>
        [Test]
        public void StandardODataLinkodataNavigationLinkTest()
        {
            // TODO unit test for the property 'StandardODataLinkodataNavigationLink'
        }
        /// <summary>
        /// Test the property 'NoneODataLinkodataNavigationLink'
        /// </summary>
        [Test]
        public void NoneODataLinkodataNavigationLinkTest()
        {
            // TODO unit test for the property 'NoneODataLinkodataNavigationLink'
        }
        /// <summary>
        /// Test the property 'OdataEditLink'
        /// </summary>
        [Test]
        public void OdataEditLinkTest()
        {
            // TODO unit test for the property 'OdataEditLink'
        }
        /// <summary>
        /// Test the property 'OdataEtag'
        /// </summary>
        [Test]
        public void OdataEtagTest()
        {
            // TODO unit test for the property 'OdataEtag'
        }
        /// <summary>
        /// Test the property 'OdataMetadataEtag'
        /// </summary>
        [Test]
        public void OdataMetadataEtagTest()
        {
            // TODO unit test for the property 'OdataMetadataEtag'
        }

    }

}
