/* 
 * Synacta
 *
 * WebApi
 *
 * OpenAPI spec version: v1
 * Contact: bhofmann@agile-is.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PrincipalSearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PrincipalSearchResultTests
    {
        // TODO uncomment below to declare an instance variable for PrincipalSearchResult
        //private PrincipalSearchResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PrincipalSearchResult
            //instance = new PrincipalSearchResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PrincipalSearchResult
        /// </summary>
        [Test]
        public void PrincipalSearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PrincipalSearchResult
            //Assert.IsInstanceOfType<PrincipalSearchResult> (instance, "variable 'instance' is a PrincipalSearchResult");
        }

        /// <summary>
        /// Test the property 'ResultType'
        /// </summary>
        [Test]
        public void ResultTypeTest()
        {
            // TODO unit test for the property 'ResultType'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CustomProperties'
        /// </summary>
        [Test]
        public void CustomPropertiesTest()
        {
            // TODO unit test for the property 'CustomProperties'
        }
        /// <summary>
        /// Test the property 'OdataContext'
        /// </summary>
        [Test]
        public void OdataContextTest()
        {
            // TODO unit test for the property 'OdataContext'
        }
        /// <summary>
        /// Test the property 'OdataReadLink'
        /// </summary>
        [Test]
        public void OdataReadLinkTest()
        {
            // TODO unit test for the property 'OdataReadLink'
        }
        /// <summary>
        /// Test the property 'FullODataLinkodataNavigationLink'
        /// </summary>
        [Test]
        public void FullODataLinkodataNavigationLinkTest()
        {
            // TODO unit test for the property 'FullODataLinkodataNavigationLink'
        }
        /// <summary>
        /// Test the property 'StandardODataLinkodataNavigationLink'
        /// </summary>
        [Test]
        public void StandardODataLinkodataNavigationLinkTest()
        {
            // TODO unit test for the property 'StandardODataLinkodataNavigationLink'
        }
        /// <summary>
        /// Test the property 'NoneODataLinkodataNavigationLink'
        /// </summary>
        [Test]
        public void NoneODataLinkodataNavigationLinkTest()
        {
            // TODO unit test for the property 'NoneODataLinkodataNavigationLink'
        }

    }

}
